apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-metrics.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "demo-metrics.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP_MESSAGE: {{ .Values.config.APP_MESSAGE | quote }}
